# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
ko:
  languageCode: ko
  languageName: 한국어
  weight: 1
  title: BaePro Portfolio
  #contentDir: content/ko
  params:
    description: 배프로의 포트폴리오

en:
  languageCode: en
  languageName: English
  weight: 2
  title: BaePro Portfolio
  #contentDir: content/en
  params:
    description: BaePro's Portfolio
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
